# Generated by Django 3.2.9 on 2021-12-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_user_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
